apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: case-study-task3
resources:
  - deployment.yaml
configMapGenerator:
  - name: task3-html-template
    files:
      - templates/index.html
    options:
      disableNameSuffixHash: true
