apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - shared-config.yaml
  - db.yaml
  - backend.yaml
  - frontend.yaml
  - networkpolicy.yaml
  - disaster-recovery.yaml
  - task6-namespace.yaml
  - task6-network-attachment.yaml
  - task6-test-pods.yaml
