# Task 4: Network security - only backend can access DB
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-default-deny-ingress
  namespace: case-study-consolidated
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - db-primary
          - db-replica
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-tier-to-db
  namespace: case-study-consolidated
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - db-primary
          - db-replica
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 5432

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-exporter-to-db
  namespace: case-study-consolidated
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - db-primary
          - db-replica
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: postgres-exporter
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-replica-to-primary
  namespace: case-study-consolidated
spec:
  podSelector:
    matchLabels:
      app: db-primary
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: db-replica
      ports:
        - protocol: TCP
          port: 5432
