apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: case-study-consolidated
type: Opaque
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppass
  DJANGO_SECRET_KEY: local-secret-key
  POSTGRES_REPL_USER: repl_user
  POSTGRES_REPL_PASSWORD: repl_pass

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-primary-init
  namespace: case-study-consolidated
data:
  01-create-replication-user.sql: |
    CREATE ROLE repl_user WITH REPLICATION LOGIN PASSWORD 'repl_pass';
  02-allow-replication.sh: |
    #!/bin/sh
    set -e
    echo "host replication repl_user 0.0.0.0/0 trust" >> "$PGDATA/pg_hba.conf"
